@startuml
package empleados {
class Empleado {
    - String cedula
    - String nombre
    - String apellido
    - String genero
    - double salario
    - LocalDate fechaNacimiento
    - LocalDate fechaIngreso
    + Empleado(String, String, String, String, double, LocalDate, LocalDate)
    + void modificarSalario(double nuevoSalario)
    + int calcularEdad()
    + double calcularPrestaciones()
    + String toString()
}

class Main {
    + void main(String[] args)
    - LocalDate obtenerFecha(String mensaje)
}

Main --> Empleado : "uso"
}
@enduml
